[package]
name = "trustlr"
version = "0.1.0"
authors = ["ygunayer"]

[dependencies]
clap = "2.30.0"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1.2"
tokio = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
